#!/bin/sh
set -e

#DEBHELPER#

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		deb-systemd-invoke try-restart acpid.service >/dev/null || true
	fi
fi
